---
controller_credentials:
  - name: Linode machine
    credential_type: Machine
    organization: Default
    inputs:
      username: root
      password: dummy

  - name: k8s - sno.escwq.xyz
    credential_type: OpenShift or Kubernetes API Bearer Token
    organization: Default
    inputs:
      host: https://api.sno.escwq.xyz:6443
      verify_ssl: false
      bearer_token: dummy

  - name: aap - sno.escwq.xyz - database
    credential_type: aap.platform_on_ocp.database
    organization: Default
    inputs:
      database_username: foobar
      database_password: foobar
      database_host: foobar
      database_port: foobar
      database_sslmode: foobar
      database_type: foobar

  - name: aap - sno.escwq.xyz - gateway
    credential_type: aap.platform_on_ocp.gateway
    organization: Default
    inputs:
      gateway_admin_password: thisisit

  - name: aap - sno.escwq.xyz - ldap
    credential_type: aap.platform_on_ocp.ldap
    organization: Default
    inputs:
      ldap_bind_username: foobar
      ldap_bind_password: foobar

  - name: aap - sno.escwq.xyz - ssl
    credential_type: aap.platform_on_ocp.ssl
    organization: Default
    inputs:
      ssl_public_cert: foobar
