apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: mario-gateway
  namespace: aap-mario
spec:
  admin_password_secret: mario-gateway-admin-password
  api:
    replicas: 2
  controller:
    disabled: false
    name: mario-controller
    no_log: true
    postgres_storage_class: lvms-vg1
    project_storage_class: lvms-vg1
    projects_existing_claim: mario-controller-pvc-projects
    route_host: mario-controller.escwq.xyz
    secret_key_secret: mario-controller-secret-key
  database:
    postgres_storage_class: lvms-vg1
  db_fields_encryption_secret: mario-gateway-encryption-secret
  eda:
    db_fields_encryption_secret: mario-eda-encryption-secret
    disabled: true
    name: mario-eda
  extra_settings:
  - setting: LOGGING['loggers']['aap']['level']
    value: DEBUG
  - setting: LOGGING['loggers']['aap.auth_audit']['level']
    value: DEBUG
  - setting: LOGGING['loggers']['ansible_base']['level']
    value: DEBUG
  - setting: LOGGING['loggers']['django']['level']
    value: DEBUG
  - setting: LOGGING['loggers']['django_auth_ldap']['level']
    value: DEBUG
  - setting: LOGGING['loggers']['django.request']['level']
    value: DEBUG
  - setting: LOGGING['loggers']['py.warnings']['level']
    value: DEBUG
  - setting: LOGGING['loggers']['rest_framework.request']['level']
    value: DEBUG
  hub:
    db_fields_encryption_secret: mario-hub-encryption-secret
    disabled: true
    file_storage_storage_class: lvms-vg1
    name: mario-hub
    no_log: true
    postgres_storage_class: lvms-vg1
    redis_storage_class: lvms-vg1
  no_log: true
  route_annotations: 'haproxy.router.openshift.io/balance: roundrobin

    haproxy.router.openshift.io/timeout: 300s

    '
  route_host: mario-aap.escwq.xyz
