apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: luigi-eda
  namespace: aap-luigi
spec:
  activation_worker:
    replicas: 2
  admin_password_secret: aap-luigi-admin-password
  admin_user: admin
  api:
    gunicorn_workers: 2
    replicas: 1
  automation_server_url: luigi-controller.escwq.xyz
  database:
    database_secret: luigi-eda-postgres-configuration
  default_worker:
    replicas: 2
  event_stream:
    gunicorn_workers: 2
    replicas: 1
  image_pull_policy: IfNotPresent
  ingress_type: Route
  no_log: true
  redis:
    replicas: 1
  route_host: luigi-eda.escwq.xyz
  scheduler:
    replicas: 2
  service_type: ClusterIP
  ui:
    replicas: 1
  worker:
    replicas: 2
