---
generate_kubemanifests_template_file_ansibleautomationplatform: "{{ inventory_dir }}/templates/ansibleautomationplatform.yml.j2"
generate_kubemanifests_template_file_automationcontroller: "{{ inventory_dir }}/templates/automationcontroller.yml.j2"
