---
controller_templates:
  - name: generate_kubemanifests
    inventory: aap_deployments
    project: aap-operator-automation
    playbook: playbooks/generate-kubemanifests.yml
    allow_simultaneous: true
