---
controller_credential_types:
  - name: aap.platform_on_ocp.gateway
    kind: cloud
    inputs:
      fields:
        - id: gateway_admin_password
          type: string
          label: AAP Gateway Admin Password
          secret: true
    injectors:
      extra_vars:
        gateway_admin_password: "{% raw %}{  { gateway_admin_password }}{% endraw %}"

  - name: aap.platform_on_ocp.database
    kind: cloud
    inputs:
      fields:
        - id: database_username
          type: string
          label: Database username
          secret: false

        - id: database_password
          type: string
          label: Database password
          secret: true

        - id: database_host
          type: string
          label: Database host
          secret: false

        - id: database_port
          type: string
          label: Database port
          secret: false

        - id: database_sslmode
          type: string
          label: Database SSL mode
          secret: false

        - id: database_type
          type: string
          label: Database type
          secret: false
    injectors:
      extra_vars:
        database_username: "{% raw %}{  { database_username }}{% endraw %}"
        database_password: "{% raw %}{  { database_password }}{% endraw %}"
        database_host: "{% raw %}{  { database_host }}{% endraw %}"
        database_port: "{% raw %}{  { database_port }}{% endraw %}"
        database_sslmode: "{% raw %}{  { database_sslmode }}{% endraw %}"
        database_type: "{% raw %}{  { database_type }}{% endraw %}"

  - name: aap.platform_on_ocp.ldap
    kind: cloud
    inputs:
      fields:
        - id: ldap_bind_username
          type: string
          label: LDAP bind username
          secret: true

        - id: ldap_bind_password
          type: string
          label: LDAP bind password
          secret: true
    injectors:
      extra_vars:
        ldap_bind_username: "{% raw %}{  { ldap_bind_username }}{% endraw %}"
        ldap_bind_password: "{% raw %}{  { ldap_bind_password }}{% endraw %}"

  - name: aap.platform_on_ocp.ssl
    kind: cloud
    inputs:
      fields:
        - id: ssl_public_cert
          type: string
          label: SSL public certificate
          secret: true
    injectors:
      extra_vars:
        ssl_public_cert: "{% raw %}{  { ssl_public_cert }}{% endraw %}"
