---
namespace: aap-25
name_gateway: myaap-gateway
name_controller: myaap-controller
name_eda: ""
name_hub: myaap-hub

ansibleautomationplatform:
  spec:
    admin_password_secret: "{{ name_controller }}-admin-password"
    controller:
      disabled: false
      name: "{{ name_controller }}"
    hub:
      disabled: false
      name: "{{ name_hub }}"
    database:
      database_secret: "{{ name_gateway }}-postgres-configuration"
    db_fields_encryption_secret: "{{ name_controller }}-secret-key"
    route_host: aap-25.escwq.xyz

automationcontroller:
  spec:
    admin_password_secret: "{{ name_controller }}-admin-password"
    api_urlpattern_prefix: controller
    postgres_configuration_secret: "{{ name_controller }}-postgres-configuration"
    secret_key_secret: "{{ name_controller }}-secret-key"

automationhub:
  spec:
    admin_password_secret: "{{ name_hub }}-admin-password"
    postgres_configuration_secret: "{{ name_hub }}-prod-postgres-configuration"

secrets:
  - name: "{{ name_gateway }}-postgres-configuration"
    data:
      host: 192.168.1.58
      port: 5415
      database: gateway
      username: postgres
      password: example
      sslmode: prefer
      type: unmanaged

  - name: "{{ name_controller }}-postgres-configuration"
    data:
      host: 192.168.1.58
      port: 5415
      database: postgres
      username: postgres
      password: example
      sslmode: prefer
      type: unmanaged

  - name: "{{ name_hub }}-postgres-configuration"
    data:
      host: 192.168.1.58
      port: 5415
      database: hub-25
      username: postgres
      password: example
      sslmode: prefer
      type: unmanaged

  - name: "{{ name_controller }}-admin-password"
    data:
      password: foobar

  - name: "{{ name_hub }}-admin-password"
    data:
      password: foobar3

  - name: "{{ name_controller }}-secret-key"
    data:
      secret_key: encryptionkey
