---
controller_templates:
  - name: generate_kubemanifests
    inventory: aap_deployments
    project: aap-operator-automation
    playbook: playbooks/generate_kubemanifests.yml
    allow_simultaneous: true

  - name: myotherplaybook
    organization: AAP24OtherOrg-dev
    inventory: "blah%3A the blah++AAP24OtherOrg-dev"
    project: aap-operator-automation-other
    playbook: playbooks/generate_kubemanifests.yml
    allow_simultaneous: true
