---
######
# General
######

ocp_namespace: aap-koopa
name_gateway: koopa-gateway
name_controller: koopa-controller
name_eda: koopa-eda
name_hub: koopa-hub
manage_kubemanifests_validate_certs: false

######
# CRs
######

ansibleautomationplatform:
  spec:
    route_host: koopa-aap.escwq.xyz
    controller:
      disabled: false
    hub:
      disabled: true
    eda:
      disabled: true
