---
######
# General
######

ocp_namespace: aap-koopa
name_gateway: koopa-gateway
name_controller: koopa-controller
name_eda: koopa-eda
name_hub: koopa-hub
manage_kubemanifests_validate_certs: false

######
# CRs
######

ansibleautomationplatform:
  spec:
    extra_settings:
      - setting: RUNTIME_FEATURE_FLAGS
        value: 'True'
    feature_flags:
      FEATURE_DASHBOARD_COLLECTION_ENABLED: true
      FEATURE_POLICY_AS_CODE_ENABLED: true
    route_host: koopa-aap.escwq.xyz
    controller:
      disabled: false
    hub:
      disabled: true
    eda:
      disabled: true
    mcp:
      disabled: false
      allow_write_operations: true
      bundle_cacert_secret: "{{ name_gateway }}-mcp-ca-bundle"
      extra_settings:
        - setting: IGNORE_CERTIFICATE_ERRORS
          value: true
      route_host: koopa-mcp.escwq.xyz
      route_tls_secret: "{{ name_gateway }}-mcp-route-tls"
    metrics:
      disabled: false
      extra_settings:
        - setting: METRICS_SERVICE_MODE
          value: 'development'

secrets:
  - metadata:
      name: "{{ name_gateway }}-mcp-route-tls"
    data:
      ca.crt: "{{ ca_crt }}"
      tls.crt: "{{ tls_crt }}"
      tls.key: jinja_tls_key

  - metadata:
      name: "{{ name_gateway }}-mcp-ca-bundle"
    data:
      bundle-ca.crt: "{{ ca_crt }}"
