# ---
# ######
# # General
# ######

# ocp_namespace: aap-mario
# name_gateway: mario-gateway
# name_controller: mario-controller
# name_eda:
# name_hub:
# manage_kubemanifests_validate_certs: false

# ######
# # CRs
# ######

# # automationcontroller:
# #   spec:
# #     admin_password_secret: "{{ name_controller }}-admin-password"
# #     postgres_configuration_secret: "{{ name_controller }}-postgres-configuration"
# #     route_host: "{{ name_controller }}.escwq.xyz"

# ansibleautomationplatform:
#   spec:
#     no_log: false
#     admin_password_secret: "{{ name_gateway }}-admin-password"
#     database:
#       postgres_storage_class: lvms-vg1
#     route_host: mario-aap.escwq.xyz
#     controller:
#       disabled: false
#       name: "{{ name_controller }}"
#     hub:
#       disabled: true
#     eda:
#       disabled: true

# ######
# # Secrets
# ######

# secrets:
#   - metadata:
#       name: "{{ name_controller }}-admin-password"
#     data:
#       password: foobar

#   - metadata:
#       name: "{{ name_controller }}-ldap-password-secret"
#     data:
#       ldap-password: password

#   - metadata:
#       name: "{{ name_gateway }}-admin-password"
#     data:
#       password: foobar
