apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: koopa-gateway
  namespace: aap-koopa
spec:
  controller:
    disabled: false
    no_log: true
    postgres_storage_class: lvms-vg1
    project_storage_class: lvms-vg1
  database:
    postgres_storage_class: lvms-vg1
  eda:
    disabled: true
  extra_settings:
  - setting: RUNTIME_FEATURE_FLAGS
    value: 'True'
  feature_flags:
    FEATURE_DASHBOARD_COLLECTION_ENABLED: true
    FEATURE_POLICY_AS_CODE_ENABLED: true
  hub:
    disabled: true
    file_storage_storage_class: lvms-vg1
    no_log: true
    postgres_storage_class: lvms-vg1
    redis_storage_class: lvms-vg1
  mcp:
    allow_write_operations: true
    bundle_cacert_secret: koopa-gateway-mcp-ca-bundle
    disabled: false
    extra_settings:
    - setting: IGNORE_CERTIFICATE_ERRORS
      value: true
    route_host: koopa-mcp.escwq.xyz
    route_tls_secret: koopa-gateway-mcp-route-tls
  metrics:
    disabled: false
    extra_settings:
    - setting: METRICS_SERVICE_MODE
      value: development
  no_log: true
  route_host: koopa-aap.escwq.xyz
