---
- tags:
    - oh-my-zsh
  become: true
  block:
    - name: Install zsh and git
      ansible.builtin.dnf:
        name:
          - zsh
          - git
        state: installed

    - name: Clone oh-my-zsh
      become: false
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/oh-my-zsh.git
        dest: ~/.oh-my-zsh

    - name: Change default shell to zsh
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

    - name: Clone dotfiles
      become: false
      ansible.builtin.git:
        repo: https://github.com/homeski/dotfiles.git
        dest: ~/dotfiles

    - name: Run dotfiles/bootstrap.sh
      become: false
      ansible.builtin.shell:
        cmd: ~/dotfiles/bootstrap.sh --force
...
