---
collections:
  - name: git+https://github.com/homeski/ansible-collection-aap-platform-on-ocp.git,main
  - name: ansible.controller
    version: '>=4.5.0,<4.6.0'
  - name: infra.controller_configuration
  - name: kubernetes.core
