---
- tags:
    - base
  become: true
  block:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname | mandatory }}"
        use: systemd

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: SSH - Disable password authentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify:
        - Restart sshd

    - name: Generic OS
      ansible.builtin.import_tasks:
        file: os-generic.yml
      when: ansible_facts.distribution != 'RedHat'

    - name: RHEL 7
      ansible.builtin.import_tasks:
        file: os-rhel7.yml
      when:
        - ansible_facts.distribution == 'RedHat'
        - ansible_facts.distribution_major_version == '7'

    - name: RHEL 8/9
      ansible.builtin.import_tasks:
        file: os-rhel-current.yml
      when:
        - ansible_facts.distribution == 'RedHat'
        - ansible_facts.distribution_major_version == '8' or ansible_facts.distribution_major_version == '9'
...
