apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mario-controller-controller-pvc-projects
  namespace: aap-mario
spec:
  accessModes:
  - ReadWriteMany
  storageClass: lvms-vg1
  volumeMode: FileSystem
  resources:
    requests:
      storage: 2000m
