apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bowser-controller-task-hpa
  namespace: aap-bowser
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bowser-controller-task
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
