---
- name: Apply Config as Code
  hosts: all
  gather_facts: false
  tasks:
    - name: Call dispatch role
      ansible.builtin.import_role:
        name: infra.aap_configuration.dispatch
      delegate_to: localhost
