- name: Curl a text file
  hosts: all
  gather_facts: false
  tasks:
    - name: Uri
      ansible.builtin.uri:
        url: http://192.168.1.58
        return_content: true
      register: uri_result

    - name: Debug
      ansible.builtin.debug:
        var: uri_result.content
