- hosts: all
  gather_facts: false
  tasks:
    - delegate_to: localhost
      block:
        - name: Query all job templates
          ansible.builtin.uri:
            url: "{{ controller_hostname }}/api/v2/job_templates"
            headers:
              Authorization: "Bearer {{ controller_token }}"
              Content-Type: application/json
            validate_certs: "{{ controller_validate_certs }}"
          register: uri_result

        - ansible.builtin.debug:
            var: uri_result.json.results

        - name: Send events to Splunk
          ansible.builtin.uri:
            method: POST
            url: "https://192.168.1.58:8088/services/collector/event"
            headers:
              Authorization: "Splunk 9646dd0b-8e5a-47ae-ae32-b633af6d7936"
            body_format: json
            body:
              event:
                job_template_id: "{{ item.id }}"
                job_template_name: "{{ item.name }}"
                organization_id: "{{ item.summary_fields.organization.id }}"
                organization_name: "{{ item.summary_fields.organization.name }}"
                pod: "{{ controller_pod }}"
            validate_certs: false
          loop: "{{ uri_result.json.results }}"
          loop_control:
            label: "{{ item.name }}"
