---
######
# General
######

ocp_namespace: aap-mario
name_gateway: mario-gateway
name_controller: mario-controller
name_eda: mario-eda
name_hub: mario-hub
manage_kubemanifests_validate_certs: false

######
# CRs
######

ansibleautomationplatform:
  spec:
    admin_password_secret: "{{ name_gateway }}-admin-password"
    api:
      replicas: 2
    db_fields_encryption_secret: "{{ name_gateway }}-encryption-secret"
    extra_settings:
      - setting: 'LOGGING[''loggers''][''aap''][''level'']'
        value: DEBUG
      - setting: 'LOGGING[''loggers''][''aap.auth_audit''][''level'']'
        value: DEBUG
      - setting: 'LOGGING[''loggers''][''ansible_base''][''level'']'
        value: DEBUG
      - setting: 'LOGGING[''loggers''][''django''][''level'']'
        value: DEBUG
      - setting: 'LOGGING[''loggers''][''django_auth_ldap''][''level'']'
        value: DEBUG
      - setting: 'LOGGING[''loggers''][''django.request''][''level'']'
        value: DEBUG
      - setting: 'LOGGING[''loggers''][''py.warnings''][''level'']'
        value: DEBUG
      - setting: 'LOGGING[''loggers''][''rest_framework.request''][''level'']'
        value: DEBUG
    controller:
      disabled: false
      name: "{{ name_controller }}"
      projects_existing_claim: "{{ name_controller }}-pvc-projects"
      route_host: mario-controller.escwq.xyz
      secret_key_secret: "{{ name_controller }}-secret-key"
    hub:
      disabled: true
      name: "{{ name_hub }}"
      db_fields_encryption_secret: "{{ name_hub }}-encryption-secret"
    eda:
      disabled: true
      name: "{{ name_eda }}"
      db_fields_encryption_secret: "{{ name_eda }}-encryption-secret"
    # route_annotations: 'haproxy.router.openshift.io/timeout: 60s'
    route_host: mario-aap.escwq.xyz

######
# PVCs
######

pvcs:
  - metadata:
      name: "{{ name_controller }}-pvc-projects"
    spec:
      resources:
        requests:
          storage: 5Gi

######
# Secrets
######

secrets:
  - metadata:
      name: "{{ name_gateway }}-admin-password"
    data:
      password: jinja_gateway_admin_password

  - metadata:
      name: "{{ name_controller }}-secret-key"
    data:
      secret_key: myencryptionkey

  - metadata:
      name: "{{ name_gateway }}-encryption-secret"
    data:
      secret_key: myencryptionkey

  - metadata:
      name: "{{ name_eda }}-encryption-secret"
    data:
      secret_key: myencryptionkey

  - metadata:
      name: "{{ name_hub }}-encryption-secret"
    data:
      database_fields.symmetric.key: "PL-MoD-KFjYE3ZmYrOmuq1rcxDqJg3w8MrYXaHQ7jQg="
