apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: bowser-controller
  namespace: aap-bowser
spec:
  admin_password_secret: bowser-controller-admin-password
  admin_user: admin
  auto_upgrade: true
  create_preload_data: false
  extra_volumes: "- name: bowser-controller-rsyslog-volume\n  configMap:\n    defaultMode:
    420\n    items:\n      - key: rsyslog.conf\n        path: rsyslog.conf\n    name:
    bowser-controller-rsyslog-configmap\n"
  garbage_collect_secrets: true
  image_pull_policy: IfNotPresent
  ingress_type: Route
  ipv6_disabled: false
  loadbalancer_ip: ''
  loadbalancer_port: 80
  loadbalancer_protocol: http
  metrics_utility_cronjob_gather_schedule: '@hourly'
  metrics_utility_cronjob_report_schedule: '@monthly'
  metrics_utility_enabled: false
  metrics_utility_pvc_claim_size: 5Gi
  no_log: true
  postgres_configuration_secret: bowser-controller-postgres-configuration
  postgres_keepalives: true
  postgres_keepalives_count: 5
  postgres_keepalives_idle: 5
  postgres_keepalives_interval: 5
  postgres_storage_class: lvms-vg1
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 1
  route_host: bowser-controller.escwq.xyz
  route_tls_termination_mechanism: Edge
  rsyslog_extra_volume_mounts: "- name: bowser-controller-rsyslog-volume\n  mountPath:
    /var/lib/awx/rsyslog/conf.d/custom.conf\n  subPath: rsyslog.conf\n"
  set_self_labels: true
  task_extra_volume_mounts: "- name: bowser-controller-rsyslog-volume\n  mountPath:
    /var/lib/awx/rsyslog/conf.d/custom.conf\n  subPath: rsyslog.conf\n"
  task_privileged: false
  web_extra_volume_mounts: "- name: bowser-controller-rsyslog-volume\n  mountPath:
    /var/lib/awx/rsyslog/conf.d/custom.conf\n  subPath: rsyslog.conf\n"
